services:
  postgres:
    container_name: postgres
    image: postgres:17.4
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: tekton
      POSTGRES_PASSWORD: S3cretPass
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  tekton:
    build:
      context: .
    container_name: tekton-challenge
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: tekton-challenge
      SERVER_PORT: 8080
      JDBC_DATABASE_URL: jdbc:postgresql://postgres:5432/postgres
      ENV_POSTGRES_USER: tekton
      ENV_POSTGRES_PASSWORD: S3cretPass
    ports:
        - "8080:8080"
volumes:
  db: